app/models.py
from tkinter import CASCADE
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, UserMixin, login
from datetime import datetime as dt

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(20), index=True)
    last_name = db.Column(db.String(20), index=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String)
    created_on = db.Column(db.DateTime, default=dt.utcnow)
    #toolboxes = db.relationship('Toolbox', backref='user', lazy=True)

    # Should return a unique identifying string
    def __repr__(self):
        return f'<user: {self.email} | {self.id}>'

    # Human readable version of repr
    def __str__(self):
        return f'<User: {self.email} | {self.first_name} {self.last_name}>'

    # hashes password for security
    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    # compares original password to hashed password
    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)
    
    def user_from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email = data['email']
        self.password = self.hash_password(data['password'])
        
    # save user to database
    def save(self):
        db.session.add(self)
        db.session.commit()

@login.user_loader 
def load_user(id):
    return User.query.get(int(id))

# one to one relationship just gets a db.ForeignKey pointing back to the table it links to
# db.relationship is used for the one to many references
class Toolbox(db.Model):
    toolbox_id = db.Column(db.Integer, primary_key=True)
    userid = db.Column(db.Integer, db.ForeignKey('user.id'))
    tools = db.relationship('Tool', backref='toolbox', lazy=True)

    def __repr__(self):
        return f'<Toolbox: {self.toolbox_id} | {self.tool_id}>'

    def __str__(self):
        return f'<Toolbox: {self.tools}>'

    # save to database
    def save(self):
        db.session.add(self)
        db.session.commit()

class Tool(db.Model):
    tool_id = db.Column(db.Integer, primary_key=True)
    toolboxid = db.Column(db.Integer, db.ForeignKey('toolbox.toolbox_id'))
    tool_name = db.Column(db.String(20), index=True, unique=False)
    tool_brand = db.Column(db.String(20), index=True, unique=False)
    quantity = db.Column(db.Integer)
    #toolboxes = db.relationship('Toolbox', backref='tool', lazy=True)

    def __repr__(self):
        return f'<Tool:  {self.tool_brand} | {self.tool_name}>'

    def __str__(self):
        return f'<Tool:  {self.tool_brand} | {self.tool_name}>'

    def tool_from_dict(self, data):
        self.tool_name = data['tool_name']
        self.tool_brand = data['tool_brand']
        self.quantity = data['quantity']
        
    # save user to database
    def save(self):
        db.session.add(self)
        db.session.commit()

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired

class NewToolForm(FlaskForm):
    tool_name = StringField('Tool Name', validators=[DataRequired()])
    tool_brand = StringField('Tool Brand', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    submit = SubmitField('Add Tool')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, UserMixin, login_required, login_user, logout_user, current_user
from flask_migrate import Migrate

# Init Plugins
db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()

def create_app(config_class=Config):
    #Init the app
    app = Flask(__name__)
    app.static_folder = "./static"
    #Link in the Config (using config_class allows swapping configs depending on environment)
    app.config.from_object(config_class)
    
    #Register plugins
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    login.login_view = 'auth.login'
    login.login_message = 'Please login to view this page'
    login.login_message_category = 'warning'

    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='')

from . import routes

app/blueprints/main/routes.py
from app.blueprints.auth.routes import login
from . import bp as main
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .forms import NewToolForm
from ...models import Tool, Toolbox, User

@main.route('/', methods=["GET"])
@login_required
def user():
    u_id = current_user.id
    mytoolbox = Toolbox.query.get(Toolbox.toolbox_id).first()
    mytools = mytoolbox.query.filter(Toolbox.tools)
    return render_template('user.html.j2', mytools=mytools)

@main.route('/newtool', methods=["GET",'POST'])
@login_required
def newtool():
    form = NewToolForm()
    if request.method == 'POST' and form.validate_on_submit():

        new_tool_data={
            "tool_name" : form.tool_name.data,
            "tool_brand" : form.tool_brand.data,
            "quantity" : form.quantity.data
        }

        new_tool_object = Tool()
        new_tool_object.tool_from_dict(new_tool_data)
        new_tool_object.save()

        new_toolbox_tool = Tool()
        new_toolbox_tool.user_id=current_user.id
#        new_toolbox_tool.toolbox_id=new_tool_object.toolbox_id
#        my_tools=Tool.query.filter_by(user_id=current_user.id).all()

        # show Tool list
        flash("Successfully Added Tool", 'success')
        return redirect(url_for('main.newtool'))
    return render_template('newTool.html.j2', form=form)

@main.route('/alltools', methods=["GET"])
@login_required
def alltools():
    tools = Tool.query.all()
    return render_template('alltools.html.j2', tools=tools)

app/templates/alltools.html.j2
{% extends "base.html.j2" %}
{% block title %}All Tools List{% endblock %}
{% block content %}
    <div class="container">
        <h1>All Tools</h1>
        <div class="container" style="background-color:lightgrey; border-radius:10px;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Tool Brand</th>
                        <th scope="col">Tool Name</th>
                        <th scope="col">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                {% for tool in tools %}
                    <tr scope="row">
                        <td>{{ tool.tool_brand }}</td>
                        <td>{{ tool.tool_name }}</td>
                        <td>{{tool.quantity}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# Bootstrap CSS #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" rel="stylesheet">
    {# Global css #} 
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
    <title>Toolbox - {% block title %}{% endblock %}</title>
</head>
<div id="front"></div><div id="back"></div>

{% include './includes/nav.html.j2' %}}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for class, message in messages %}
            <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

app/templates/includes/nav.html.j2
<!--Bootstrap Nav Bar-->
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Toolbox</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.edit_profile')}}">
                    <i class="bi bi-gear-wide-connected"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('main.user')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.newtool')}}">Add a Tool</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.signup')}}">Sign Up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Log In</a>
            </li>
            {% endif %}
        </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<!--End Bootstrap Nav bar-->

app/templates/login.html.j2
{% extends 'base.html.j2' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form action="{{url_for('auth.login')}}" method="POST">
        {{form.hidden_tag()}}
        <div>
            <!--The class= attributes passed into the fields is bootstrap css-->
            {{form.email.label(class="form-label")}}
            {{form.email(class="form-control")}}
        </div>
        <div>
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control")}}
        </div>
        <br>
        <div>
            {{form.submit(class="btn btn-primary form-control")}}
        </div>
    </form>
</div>
{% endblock %}

app/templates/newTool.html.j2
{% extends "base.html.j2" %}
{% block title %}Add Tool{% endblock %}
{% block content %}
    <div class="container">        
        <h2>Add a Tool</h2>
            <form action="{{url_for('main.newtool')}}" method="POST">
            {{form.hidden_tag()}}
            <div>
                <!--The class= attributes passed into the fields is bootstrap css-->
                {{form.tool_name.label(class="form-label")}}
                {{form.tool_name(class="form-control")}}
            </div>
            <div>
                {{form.tool_brand.label(class="form-label")}}
                {{form.tool_brand(class="form-control")}}
            </div>
            <div>
                {{form.quantity.label(class="form-label")}}
                {{form.quantity(class="form-control")}}
            </div>
            <br>
            <div>
                {{form.submit(class="btn btn-primary form-control")}}
            </div>
            </form>
    </div>
{% endblock %}

app/templates/signup.html.j2
{% extends 'base.html.j2' %}

{% block title %}
    <!--Below code checks to see if someone is logged in to determine if they
    get the Signup form or the edit_profile form-->
    {% if current_user.is_authenticated %}
        Update Profile
    {% else %}
        Signup
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
    <h1>
        {% if current_user.is_authenticated %}
            Update Profile
        {% else %}
            Sign up
        {% endif %}
    </h1>
        <form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.signup')}}" method="POST">
            {{form.hidden_tag()}}
            <div>
                <!--The class= attributes passed into the fields is bootstrap css-->
                {{form.first_name.label(class="form-label")}}
                                                        <!--value below shows field contents on the edit form if user is logged in.  If not, it will show blank on the registration form-->
                {{form.first_name(class="form-control", value=current_user.first_name)}}
                {% for error in form.first_name.errors %}
                    <small style="color:red;">{{error}}</small> 
                {% endfor %}
            </div>
            <div>
                {{form.last_name.label(class="form-label")}}
                {{form.last_name(class="form-control", value=current_user.last_name)}}
                {% for error in form.last_name.errors %}
                    <small style="color:red;">{{error}}</small> 
                {% endfor %}
            </div>
            <div>
                {{form.email.label(class="form-label")}}
                {{form.email(class="form-control", value=current_user.email)}}
                {% for error in form.email.errors %}
                    <small style="color:red;">{{error}}</small> 
                {% endfor %}
            </div>
            <div>
                {{form.password.label(class="form-label")}}
                {{form.password(class="form-control")}}
                {% for error in form.password.errors %}
                    <small style="color:red;">{{error}}</small> 
                {% endfor %}
            </div>
            <div>
                {{form.confirm_password.label(class="form-label")}}
                {{form.confirm_password(class="form-control")}}
                {% for error in form.confirm_password.errors %}
                    <small style="color:red;">{{error}}</small> 
                {% endfor %}
            </div>
            <br>
            <div>
                {{form.submit(class="btn btn-primary form-control")}}
            </div>
        </form>
    </div>
{% endblock %}

app/templates/user.html.j2
{% extends "base.html.j2" %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <div class="container">
        <h1>Toolbox Home</h1>
        <h2>Welcome {{ current_user.first_name }} {{ current_user.last_name }} to your ToolBox</h2>
            <p> {% for tool in mytools %}
                    {{ tool.tool_brand }}
                    {{ tool.tool_name }}
                {% endfor %}
            </p>
        <a href="{{url_for('main.alltools')}}">See all available tools</a>
    </div>
{% endblock %}